# Generated by Django 4.2.3 on 2023-07-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibonaccinumber',
            name='calculation_identifier',
            field=models.CharField(default='initial_calculation', max_length=100),
        ),
    ]
