# Generated by Django 4.2.3 on 2023-07-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0002_fibonaccinumber_calculation_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonaccinumber',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=1000),
        ),
    ]
