# Generated by Django 4.2.3 on 2023-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0003_alter_fibonaccinumber_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibonaccinumber',
            name='fibonacci_sequence',
            field=models.CharField(default='initial_calculation', max_length=200),
        ),
    ]
