# Generated by Django 4.2.3 on 2023-07-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0004_fibonaccinumber_fibonacci_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibonaccinumber',
            old_name='value',
            new_name='input_number',
        ),
    ]
